### ISSUE TITLE
type object 'HPE3ParClient' has no attribute 'getPortNumber'

### ISSUE THREAD

**Issue by ckurka** [HewlettPackard/hpe3par_ansible_module#62]
Ansible Version 2.8.2
Python Version 3.6.3
hpe3par-sdk       1.2.1
python-3parclient 4.2.11

When trying to create an online clone against Primera I receive the following error message using the latest modules, and SDK. This also fails against a 3Par in the same manner. Older versions work with 3Par, but not Primera

The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1582743385.0328465-6801247984569/AnsiballZ_hpe3par_online_clone.py", line 114, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1582743385.0328465-6801247984569/AnsiballZ_hpe3par_online_clone.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1582743385.0328465-6801247984569/AnsiballZ_hpe3par_online_clone.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_hpe3par_online_clone_payload_FkwD1j/__main__.py", line 400, in <module>
  File "/tmp/ansible_hpe3par_online_clone_payload_FkwD1j/__main__.py", line 370, in main
AttributeError: type object 'HPE3ParClient' has no attribute 'getPortNumber'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1582743385.0328465-6801247984569/AnsiballZ_hpe3par_online_clone.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1582743385.0328465-6801247984569/AnsiballZ_hpe3par_online_clone.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1582743385.0328465-6801247984569/AnsiballZ_hpe3par_online_clone.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_hpe3par_online_clone_payload_FkwD1j/__main__.py\", line 400, in <module>\n  File \"/tmp/ansible_hpe3par_online_clone_payload_FkwD1j/__main__.py\", line 370, in main\nAttributeError: type object 'HPE3ParClient' has no attribute 'getPortNumber'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

Here is the task I am running in the Playbook

  - name: Create Clone clone_volume_ansible
      hpe3par_online_clone:
        storage_system_ip="10.10.253.190"
        storage_system_username="3paradm"
        storage_system_password="3pardata"
        state=present
        clone_name="{{osflavor}}"
        base_volume_name="{{osbase}}"
        dest_cpg="SSD_r6"
        tpvv=false
        tdvv=False
        compression=False
        snap_cpg="SSD_r6"

**Comment by chrisarnott86** [comment]
I have found exactly the same issue. I had to go back to commit a1e2b40b to get it working

**Comment by ckurka** [comment]
Thanks! I'll give that a try
